### ISSUE TITLE
gradle插件内引用了三方的lib报错问题

### ISSUE THREAD

**Issue by moonljt521** [llew2011/BytecodeFixer#1]
您好，在自定义的gradle插件的module 内 又引用了三方的库，比如javassist ，我将这个插件先传到了本地仓库，比如
uploadArchives {
    repositories {
        mavenDeployer {
            repository(url: uri("../rep"))

            pom.groupId = GROUP_ID
            pom.artifactId = "EventTrackingPlugin"
            pom.version = EVENT_TRACKING_VERSION
        }
    }
}
上传成功了，但是，测试加载这个插件的时候，报错了
Unable to load class 'com.moon.gradle.EventTrackingPlugin'.
Possible causes for this unexpected error include:<ul><li>Gradle's dependency cache may be corrupt (this sometimes occurs after a network connection timeout.)
Re-download dependencies and sync project (requires network)</li><li>The state of a Gradle build process (daemon) may be corrupt. Stopping all Gradle daemons may solve this problem.
Stop Gradle build processes (requires restart)</li><li>Your project may be using a third-party plugin which is not compatible with the other plugins in the project or the version of Gradle requested by the project.</li></ul>In the case of corrupt Gradle processes, you can also try closing the IDE and then killing all Java processes.

我的配置是没有问题，我用相同的方式上传并加载另一个插件是成功的（不同的是那个插件没有用到什么三方库）。

这个error 我Google过，StackOverflow上的解答没有解决我的问题。

求教，怎么解决~
我想知道您是怎么上传到仓库的，我感觉上传到jcenter 或者本地maven应该形式差不多。

我用的是as3.1（强制使用了gradle4.4）

**Comment by llew2011** [comment]
@moonljt521 
我使用的是这个：classpath 'com.novoda:bintray-release:0.3.4'

**Comment by llew2011** [comment]
@moonljt521 
我的仓库配置在本地也是OK的，你可以发个demo到我邮箱：337b76594@gmail.com，我帮你看一下
