### ISSUE TITLE
在injector中没有fixedclassFile

### ISSUE THREAD

**Issue by soulrelay** [llew2011/BytecodeFixer#2]
使用github上的代码简单测试了一下 反编译查看apk的确修复成功了 但是在injector中却没有如文章中修复的类的文件 我看如果配置了keepFixedClassFile，并不会清除修复的类文件。我配置的是true  但是看不到fixedclassFile

**Comment by llew2011** [comment]
刷新一下目录

**Comment by llew2011** [comment]
刷新一下injector目录
