### ISSUE TITLE
[source error] no such field

### ISSUE THREAD

**Issue by lujun525** [llew2011/BytecodeFixer#3]
'com.tencent.av.sdk.NetworkHelp##getMobileAPInfo(android.content.Context,int)##if(0 != ContextCompat.checkSelfPermission($1, Manifest.permission.READ_PHONE_STATE)){System.out.println("i have hooked this method by BytecodeFixer !!!");return "权限没打开";}##0'

楼主你好：我尝试在app.build里添加以上文件编译会报错，说找不到PackageManager和ContextCompat这个类，报以下错误
javassist.CannotCompileException: [source error] no such field: PackageManager/PERMISSION_GRANTED。

直接用下面是可以编译通过的
'com.tencent.av.sdk.NetworkHelp##getMobileAPInfo(android.content.Context,int)##if(Boolean.TRUE.booleanValue()){System.out.println("i have hooked this method by BytecodeFixer !!!");return "检查权限";}##0'

还有看源代码，build.gradle里配置了dependencies，代码里也没有用到这个，谢谢楼主解答下

**Comment by llew2011** [comment]
#### fixConfig里使用的类除了基本类型外其它类都要写全路径
- ContextCompat
要写成  `android.support.v4.content.ContextCompat`
- Manifest 
要写成  `android.Manifest`

**Comment by llew2011** [comment]
> 'com.tencent.av.sdk.NetworkHelp##getMobileAPInfo(android.content.Context,int)##if(0 != ContextCompat.checkSelfPermission($1, Manifest.permission.READ_PHONE_STATE)){System.out.println("i have hooked this method by BytecodeFixer !!!");return "权限没打开";}##0'
> 
> 楼主你好：我尝试在app.build里添加以上文件编译会报错，说找不到PackageManager和ContextCompat这个类，报以下错误
> javassist.CannotCompileException: [source error] no such field: PackageManager/PERMISSION_GRANTED。
> 
> 直接用下面是可以编译通过的
> 'com.tencent.av.sdk.NetworkHelp##getMobileAPInfo(android.content.Context,int)##if(Boolean.TRUE.booleanValue()){System.out.println("i have hooked this method by BytecodeFixer !!!");return "检查权限";}##0'
> 
> 还有看源代码，build.gradle里配置了dependencies，代码里也没有用到这个，谢谢楼主解答下

源代码里的dependencies没有使用，多谢提醒，这是个bug，稍后会做修复

**Comment by llew2011** [comment]
使用1.0.8版本
